<a href="https://colab.research.google.com/github/dhoneshruti59-cloud/task24/blob/main/task24_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving student performance dataset.csv to student performance dataset.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
filepath="/content/student performance dataset.csv"
df=pd.read_csv("student performance dataset.csv")

In [ ]:
df.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  1000 non-null   int64
 1   gender                      1000 non-null   object
 2   study_time_hours            1000 non-null   float64
 3   attendance_percent          1000 non-null   float64
 4   sleep_hours                 1000 non-null   float64
 5   parental_education          898 non-null    object
 6   internet_access             1000 non-null   object
 7   extracurricular_activities  1000 non-null   object
 8   part_time_job               1000 non-null   object
 9   previous_grade              1000 non-null   float64
 10  final_exam_score            1000 non-null   float64
 11  final_grade                 1000 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 93.9+ KB

In [ ]:
df.isnull().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [ ]:
df.drop_duplicates()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [ ]:
X=df.drop('final_grade',axis=1)
X.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3

In [ ]:
y=df['final_grade']
y.head()

0    A
1    A
2    A
3    B
4    D
Name: final_grade, dtype: object

In [ ]:
print("Shape of X:",X.shape)
print("Shape of y:",y.shape)

Shape of X: (1000, 11)
Shape of y: (1000,)

In [ ]:
X=pd.get_dummies(X,drop_first=True)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler

In [ ]:
from sklearn.model_selection import train_test_split
X_train, y_train, X_test, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("shape of X_train:",X_train.shape)
print("shape of X_test:",X_test.shape)
print("shape of y_train:",y_train.shape)
print("shape of y_test",y_test.shape)

shape of X_train: (800, 13)
shape of X_test: (800,)
shape of y_train: (200, 13)
shape of y_test (200,)