<a href="https://colab.research.google.com/github/dhoneshruti59-cloud/task24/blob/main/task24_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [2]:
from google.colab import files
uploaded=files.upload()

Saving heart.csv to heart.csv

In [3]:
filepath="/content/heart.csv"
df=pd.read_csv("/content/heart.csv")

In [4]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [6]:
X=df.drop('HeartDisease',axis=1)
X.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up

In [7]:
y=df['HeartDisease']
y.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [10]:
print("Shape of X:",X.shape)
print("Shape of y:",y.shape)

Shape of X: (918, 11)
Shape of y: (918,)

In [16]:
X=pd.get_dummies(X,drop_first=True)

In [17]:
X_train, X_test,y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [24]:
lr=LogisticRegression()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred))
print("\nConfusion_matrix:",confusion_matrix(y_test, y_pred))
print("\nClassification report:",classification_report(y_test, y_pred))

Accuracy: 0.8478260869565217

Confusion_matrix: [[66 11]
 [17 90]]

Classification report:               precision    recall  f1-score   support

           0       0.80      0.86      0.82        77
           1       0.89      0.84      0.87       107

    accuracy                           0.85       184
   macro avg       0.84      0.85      0.85       184
weighted avg       0.85      0.85      0.85       184

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [25]:
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt=dt.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred_dt))
print("\nConfusion_matrix:",confusion_matrix(y_test, y_pred_dt))
print("\nClassification report:",classification_report(y_test, y_pred_dt))

Accuracy: 0.8260869565217391

Confusion_matrix: [[62 15]
 [17 90]]

Classification report:               precision    recall  f1-score   support

           0       0.78      0.81      0.79        77
           1       0.86      0.84      0.85       107

    accuracy                           0.83       184
   macro avg       0.82      0.82      0.82       184
weighted avg       0.83      0.83      0.83       184

In [26]:
svm=SVC()
svm.fit(X_train, y_train)
y_pred_svm=svm.predict(X_test)
print("Accuracy:",accuracy_score(y_test, y_pred_svm))
print("\nConfusion_matrix:",confusion_matrix(y_test, y_pred_svm))
print("\nClassification report:",classification_report(y_test, y_pred_svm))

Accuracy: 0.6847826086956522

Confusion_matrix: [[54 23]
 [35 72]]

Classification report:               precision    recall  f1-score   support

           0       0.61      0.70      0.65        77
           1       0.76      0.67      0.71       107

    accuracy                           0.68       184
   macro avg       0.68      0.69      0.68       184
weighted avg       0.69      0.68      0.69       184

In [27]:
knn=KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred_knn=knn.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred_knn))
print("\nConfusion_matrix:",confusion_matrix(y_test, y_pred_knn))
print("\nClassification report:",classification_report(y_test, y_pred_knn))

Accuracy: 0.7065217391304348

Confusion_matrix: [[55 22]
 [32 75]]

Classification report:               precision    recall  f1-score   support

           0       0.63      0.71      0.67        77
           1       0.77      0.70      0.74       107

    accuracy                           0.71       184
   macro avg       0.70      0.71      0.70       184
weighted avg       0.71      0.71      0.71       184

In [28]:
nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred_nb))
print("\nConfusion_matrix:",confusion_matrix(y_test, y_pred_nb))
print("\nClassification report:",classification_report(y_test, y_pred_nb))

Accuracy: 0.8586956521739131

Confusion_matrix: [[68  9]
 [17 90]]

Classification report:               precision    recall  f1-score   support

           0       0.80      0.88      0.84        77
           1       0.91      0.84      0.87       107

    accuracy                           0.86       184
   macro avg       0.85      0.86      0.86       184
weighted avg       0.86      0.86      0.86       184

In [29]:
comparison=pd.DataFrame({
    "Model":[
        "Logistic Regression",
        "Decision Tree",
        "SVM",
        "KNN",
        "Naive Bayes"
    ], "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_svm),
        accuracy_score(y_test, y_pred_knn),
        accuracy_score(y_test, y_pred_nb)
    ],
    "Precision": [
        precision_score(y_test, y_pred),
        precision_score(y_test, y_pred_dt),
        precision_score(y_test, y_pred_svm),
        precision_score(y_test, y_pred_knn),
        precision_score(y_test, y_pred_nb)
    ],
    "Recall": [
        recall_score(y_test, y_pred),
        recall_score(y_test, y_pred_dt),
        recall_score(y_test, y_pred_svm),
        recall_score(y_test, y_pred_knn),
        recall_score(y_test, y_pred_nb)
    ],
    "F1 Score": [
        f1_score(y_test, y_pred),
        f1_score(y_test, y_pred_dt),
        f1_score(y_test, y_pred_svm),
        f1_score(y_test, y_pred_knn),
        f1_score(y_test, y_pred_nb)
    ]
})

comparison

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.847826   0.891089  0.841121  0.865385
1        Decision Tree  0.826087   0.857143  0.841121  0.849057
2                  SVM  0.684783   0.757895  0.672897  0.712871
3                  KNN  0.706522   0.773196  0.700935  0.735294
4          Naive Bayes  0.858696   0.909091  0.841121  0.873786